// TODO: Replace with file generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP3NHk4kogH_bR8D1FqzyswfOQ2_32x4I',
    appId: '1:689975441365:web:901fb763083d3df29daf5c',
    messagingSenderId: '689975441365',
    projectId: 'fir-flutter-codelab-a9cb1',
    authDomain: 'fir-flutter-codelab-a9cb1.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-a9cb1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBptjdaZK266Q2Ksq7aEITBaE4bXVsHEx4',
    appId: '1:689975441365:android:937d4d2de32e32799daf5c',
    messagingSenderId: '689975441365',
    projectId: 'fir-flutter-codelab-a9cb1',
    storageBucket: 'fir-flutter-codelab-a9cb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJedAR32BiS7HpGEqV5KC8arMkhAxwfhk',
    appId: '1:689975441365:ios:4fbf2d84d44c8af79daf5c',
    messagingSenderId: '689975441365',
    projectId: 'fir-flutter-codelab-a9cb1',
    storageBucket: 'fir-flutter-codelab-a9cb1.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJedAR32BiS7HpGEqV5KC8arMkhAxwfhk',
    appId: '1:689975441365:ios:4fbf2d84d44c8af79daf5c',
    messagingSenderId: '689975441365',
    projectId: 'fir-flutter-codelab-a9cb1',
    storageBucket: 'fir-flutter-codelab-a9cb1.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

}